// Blog posts data - add new articles here
// Each article will be auto-generated by scheduled content tasks

export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: 'state-guide' | 'exposure-site' | 'medical' | 'veteran' | 'legal-process';
  publishedAt: string;
  updatedAt?: string;
  author: string;
  readTime: string;
  keywords: string[];
  content: string;
}

export const BLOG_POSTS: BlogPost[] = [
  // Example structure - new posts will be added here by automated content tasks
  // {
  //   slug: "texas-mesothelioma-laws-complete-guide",
  //   title: "Texas Mesothelioma Laws: Complete 2026 Guide",
  //   description: "Everything you need to know about filing a mesothelioma lawsuit in Texas...",
  //   category: "state-guide",
  //   publishedAt: "2026-01-27",
  //   author: "Mesothelioma Lawyer Nearby",
  //   readTime: "12 min read",
  //   keywords: ["texas mesothelioma lawyer", "texas asbestos laws", "texas statute of limitations"],
  //   content: `...full article content...`
  // }
];

// Helper to get post by slug
export const getPostBySlug = (slug: string): BlogPost | undefined => {
  return BLOG_POSTS.find(post => post.slug === slug);
};

// Helper to get posts by category
export const getPostsByCategory = (category: BlogPost['category']): BlogPost[] => {
  return BLOG_POSTS.filter(post => post.category === category);
};

// Helper to get recent posts
export const getRecentPosts = (limit: number = 5): BlogPost[] => {
  return [...BLOG_POSTS]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit);
};
